"""Replace username to nickname

Revision ID: d77e2666d009
Revises: af2a035a01c3
Create Date: 2025-08-06 16:56:53.554795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d77e2666d009"
down_revision: Union[str, Sequence[str], None] = "af2a035a01c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Users", sa.Column("nickname", sa.String(length=30), nullable=False))
    op.drop_column("Users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Users",
        sa.Column(
            "username", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("Users", "nickname")
    # ### end Alembic commands ###
